In [1]:
import torch
import torch.nn as nn

In [2]:
X = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float)
# A tensor named X is created
# It represents a matrix with two rows and three columns
# Each element is represented with floating-point numbers

In [3]:
X # Check tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [4]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.hidden = nn.Linear(3, 50)  # Creates a linear layer with input size 3 and output size 50
        self.output = nn.Linear(50, 1)  # Creates a linear layer with input size 50 and output size 1
        self.tanh = nn.Tanh()  # Creates a Tanh activation function layer that applies Tanh activation function to inputs
        self.sigmoid = nn.Sigmoid()  # Creates a Sigmoid activation function layer that applies Sigmoid activation function to inputs

    def tanh(self, x):
        return (torch.exp(x) - torch.exp(-x)) / (torch.exp(x) + torch.exp(-x))  # Computes the Tanh activation function

    def sigmoid(self, x):
        return 1 / (1 + torch.exp(-x))  # Computes the Sigmoid activation function

    def forward(self, x):
        x = self.tanh(self.hidden(x))  # Applies Tanh activation function to inputs and applies the hidden layer
        x = self.sigmoid(self.output(x))  # Applies Sigmoid activation function to inputs and applies the output layer

        return x  # Returns the output


In [5]:
torch.manual_seed(1)  # Sets the random seed of the torch module to 1 for reproducibility
net = Net()  # Creates an instance of the 'Net' class called 'net'
output = net(X)  # Computes an output ('output') using the 'net' object with input 'X'
print(output)  

tensor([[0.4892],
        [0.5566]], grad_fn=<MulBackward0>)


In [6]:
torch.manual_seed(190401008)  # Setting the random seed of the torch module to my student ID
net = Net()
output = net(X)
print(output)

tensor([[0.4929],
        [0.5002]], grad_fn=<MulBackward0>)
